# Generated by Django 4.2.3 on 2023-07-04 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_language_customuser_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='location',
            new_name='roach',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='language',
            field=models.CharField(blank=True, choices=[('en', 'English'), ('uk', 'Ukrainian'), ('es', 'Spanish'), ('fr', 'French'), ('de', 'German'), ('it', 'Italian')], max_length=50),
        ),
    ]
